name: Auto Scanner Bolas Global

on:
  schedule:
    # Se ejecutará cada hora desde las 14:00 hasta las 21:00 UTC 
    # (Equivale de 9:00 AM a 4:00 PM hora de Lima) de lunes a viernes
    - cron: '0 14-21 * * 1-5'
  workflow_dispatch:

jobs:
  run-scanner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          pip install requests pandas yfinance lxml html5lib

      - name: Ejecutar script autónomo
        run: |
          python main.py
